### ISSUE TITLE
go install  mistake

### ISSUE THREAD

**Issue by MySweetMemories** [gwen001/github-subdomains#13]
when i excute the command that go install , i got a reply that go: github.com/bobesa/go-domain-util@v0.0.0-20190911083921-4033b5f7dd89: Get https://proxy.golang.org/github.com/bobesa/go-domain-util/@v/v0.0.0-20190911083921-4033b5f7dd89.mod: dial tcp 142.251.42.241:443: i/o timeout.
how can I solve it ,
![image](https://user-images.githubusercontent.com/68830738/134646178-5946958a-015f-4b28-81e8-625b095e0bad.png)

**Comment by mjasec** [comment]
the same as me unfortunately on wsl not working DO it on vm machine

**Comment by gwen001** [comment]
Should be fixed now. Sorry for being late...
