### ISSUE TITLE
Out of date installation instructions

### ISSUE THREAD

**Issue by GreenPoint-InfoSec** [gwen001/github-subdomains#14]
The installation instructions appear to be out of date. The `go get` command did not work. Using: `go install github.com/gwen001/github-subdomains@master` seems to be the correct way to install it now.

**Comment by Kaoliverda** [comment]
that command only install it as a file, what am i suppose to do after that to make the tool work? both of the original two ways of installation didn't work for me

**Comment by gwen001** [comment]
Should be fixed now. Sorry for being late...
