### ISSUE TITLE
Due to new search API tools is not working properly

### ISSUE THREAD

**Issue by yashanand** [gwen001/github-subdomains#15]
This is generated by the tools which is giving error 
https://api.github.com/search/code?per_page=100&s=indexed&type=Code&o=desc&q=%22google.com%22&page=1
![image](https://user-images.githubusercontent.com/21155589/151405681-b2227ac8-bd7c-4ed9-926a-f2217ec3ec9f.png)

**Comment by AmeerAssadi** [comment]
This happened because you didn’t provide a github token, you should use the tool as following
github-subdomains -d domain.com -o output.txt -t token1, token2, token3
