### ISSUE TITLE
new pattern token

### ISSUE THREAD

**Issue by vansh1** [gwen001/github-subdomains#18]
please add token support for new beta version github-tokens which is like this "github_pat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

**Comment by devopscoder331** [comment]
Hi, pending appove [PR](https://github.com/gwen001/github-subdomains/pull/20) that adds a match to the new token format (PAT) to the regular expression

**Comment by devopscoder331** [comment]
@vansh1 you can use my [fork](https://github.com/devopscoder331/github-subdomains) , it fixed the regular expression and added the Dockefile

**Comment by gwen001** [comment]
Fixed, thank you and sorry for the delay!
