### ISSUE TITLE
github-subdomains command does not found

### ISSUE THREAD

**Issue by iamhassanraza99** [gwen001/github-subdomains#21]
The file "github-subdomains" disappeared after this commands "go install" in github-subdomains directory.

Output of "go install" command:
      go: downloading github.com/jpillora/go-tld v1.0.0
      go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
      go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381

While executing command "github-subdomains -d example.com", the error shows that "github-subdomains command not found"

**Comment by gwen001** [comment]
As said in the readme, install steps are:

````
go install github.com/gwen001/github-subdomains@latest
````

OR

````
git clone https://github.com/gwen001/github-subdomains
cd github-subdomains
go install
````

I cannot predict the result if you do both or different. Also make sure that the bin Go path is in your executable path.

Thank you.

**Comment by iamhassanraza99** [comment]
this was the problem "Also make sure that the bin Go path is in your executable path". It worked. Thank you.
