### ISSUE TITLE
don't work for me 

### ISSUE THREAD

**Issue by snepedz** [gwen001/github-subdomains#22]
hi ,
can you help me 
![sssss](https://user-images.githubusercontent.com/29075786/225006447-7a7decae-e529-43ea-a860-bd414dc8ce08.png)

**Comment by Kawal0508** [comment]
I am having the same problem!! is there any solution to it 
@gwen001
@snepedz
 @DOLORESH4Z3

**Comment by gwen001** [comment]
Might be related to your environment.
Check variables GOPATH, GOROOT. Also make sure your go bin directory is in your PATH, something like `PATH=/home/xxxxx/go/bin`

**Comment by dg-entelgy** [comment]
This is because the binaries are installed on a /go/bin folder either on the root folder or the user you're as at installation. You need to create a symbolic link or add that folder to your path. For example ln -s /root/go/bin/github-subdomain /usr/bin/github-subdomain

**Comment by 0xtaffy** [comment]
Add the following to your .bashrc "export PATH=$PATH:$HOME/go/bin" to add the /go/bin folder to your PATH or run the export whenever you want to run the tool.

**Comment by gwen001** [comment]
Not related to that script, sorry.
https://www.linuxjournal.com/content/how-set-or-modify-path-variable-linux
