### ISSUE TITLE
Token not Found

### ISSUE THREAD

**Issue by jayraj0x01** [gwen001/github-subdomains#26]
Hello, thanks for this project... I used to use this program before but after installing the new version it doesn't work. my problem is entirely related to the github token. I'm creating a token at https://github.com/settings/tokens . but it says that the token was not found even though I used the token with the -t parameter.

![error](https://github.com/gwen001/github-subdomains/assets/146564694/97dd35c2-89d5-4513-9255-35ea65675fc1)

**Comment by jayraj0x01** [comment]
Help !!!!!!
@gwen001

**Comment by Derv83** [comment]
Am experiencing the same issue....tried creating a .tokens file but to no avail.............well  shoot...it did work after i ran "go run main.go -d ******.com" try that @jayraj0x01

**Comment by gwen001** [comment]
If you cloned the directory the `.tokens` file should be placed in this directory.
If you installed the program through `go install ...` the `.tokens` file should be placed in the directory you are running the program.
If you use an environment variable, you can set several tokens separated by commas: `token1,token2,token3...`

Regarding the initial issue, the regexp used to parse the tokens is: `[0-9a-f]{40}|ghp_[a-zA-Z0-9]{36}|github_pat_[_a-zA-Z0-9]{82}` , check if your token fit the regexp, if not, just let me know so I could update it.
