### ISSUE TITLE
tool not using all the tokens from .bashrc

### ISSUE THREAD

**Issue by balook** [gwen001/github-subdomains#9]
i embedded 3 tokens in bashrc like export githb_token=tok1n,tok2,tok3 
but the tool only showing  [09:25:14] Tokens:1, Delay:2200ms  where as in github-regexp tool is showing [09:25:35] Tokens:3, Delay:866ms so there is a fix needed in github-subdomains tool

**Comment by nativepentesters** [comment]
i think you did some spelling mistake. it should be like this:
GITHUB_TOKEN=

**Comment by balook** [comment]
@gwen001 take a look into this issue

**Comment by balook** [comment]
> i think you did some spelling mistake. it should be like this:
> GITHUB_TOKEN=
Yeah I have the same way. ....

**Comment by gwen001** [comment]
```
echo "export GITHUB_TOKEN=token1,token2,token3" >> ~/.bashrc
source ~/.bashrc
```

Works pretty well.
